### ISSUE TITLE
agregar soporte para el protocolo OAI-PMH

### ISSUE THREAD

**Issue by AR4Z** [dsvalenciah/roap#29]
para que la federación puede hacer cosechado de roap

**Comment by dsvalenciah** [comment]
### En este momento se están soportando 4 operaciones básicas a nivel de un objeto de aprendizaje, de este modo se pretende dar soporte a la parte de OAI-PMH que necesitamos. Las operaciones son las siguientes:
**1. crear objeto de aprendizaje a partir de contenido XML.**
**2. crear objeto de aprendizaje a partir de contenido JSON.**
**3. obtener objeto de aprendizaje con contenido XML.**
**4. obtener objeto de aprendizaje con contenido JSON.**

A continuación se muestran algunos ejemplos de cómo se debe consumir la API para ejecutar las operaciones anteriormente mostradas:

**1. crear objeto de aprendizaje con contenido XML:**
```sh
curl -X POST \
  your_host/v1/learning-object-collection \
  -H 'Authorization: JWT' \
  -H 'Content-Type: application/json' \
  -d '{
    "format": "xml",
    "category": "some_category",
    "metadata": "xml_content_as_string",
    "file": {
        "mimeType": "mimetype",
        "name": "string",
        "size": "integer",
        "lastModified": "timestamp_datetime_integer",
        "base64File": "a_base_64_file_content_encoded_as_string"
    }
}'
// returns {"id": "created_learning_object_id} with content-type → application/json
```

**2. crear objeto de aprendizaje a partir de contenido JSON:**
```sh
curl -X POST \
  your_host/v1/learning-object-collection \
  -H 'Authorization: JWT' \
  -H 'Content-Type: application/json' \
  -d '{
    "format": "json",
    "category": "some_category",
    "metadata": {
        "some": "data_as_JSON"
    },
    "file": {
        "mimeType": "mimetype",
        "name": "string",
        "size": "integer",
        "lastModified": "timestamp_datetime_integer",
        "base64File": "a_base_64_file_content_encoded_as_string"
    }
}'
// returns {"id": "created_learning_object_id} with content-type → application/json
```

**3. obtener objeto de aprendizaje con contenido XML (solo metadatos):**
```sh
curl -X GET \
  'your_host/v1/learning-object-collection/learning_object_id?format=xml' \
  -H 'Authorization: JWT' \
// returns xml_body_text with content-type → text/xml
````

**4. obtener objeto de aprendizaje con contenido JSON  (solo metadatos):**
```sh
curl -X GET \
  'your_host/v1/learning-object-collection/learning_object_id?format=json' \
  -H 'Authorization: JWT' \
// returns json with content-type → application/json
```

**Nota**
Si se trata de obtener un objeto de aprendizaje sin especificar el parámetro `format`, entonces el resultado será toda la información de un objeto de aprendizaje, por ejemplo:
```sh
curl -X GET \
  'your_host/v1/learning-object-collection/learning_object_id' \
  -H 'Authorization: JWT' \
// returns json with content-type → application/json
```

La pregunta que tengo es, ¿Se necesita alguna otra operación más para poder soportar el cosechado de ROAP @AR4Z ?
